### PR TITLE
Fixbug Fixing "urls" to support Django 4, older versions Fixes #254

### LINKED ISSUE #254: Quick fix to enable this package to work with Django 4 and the older versions
Hi There, 
would it be possible to add this line of code within the "rest_framework_social_oauth2/urls.py" file. This helps with Django4.0 and would also work with the older version.

Replace
```
from django.conf.urls import url, include

```
To
```
from django.conf.urls import include
try:
    from django.conf.urls import url
except ImportError:
    from django.urls import re_path as url


```

### PR DESCRIPTION
**Pull request by islam-kamel**
This helps with Django4.0 and would also work with the older version.

Replace
```python
from django.conf.urls import url, include
```
To
```python
from django.conf.urls import include
try:
    from django.conf.urls import url
except ImportError:
    from django.urls import re_path as url
```

### CODE REVIEW

**Review by huxaiphaer — APPROVED** [review]
LGTM, We kindly need this fix for Django 4+

**Review by kntiwary — APPROVED** [review]
This is much needed

**Comment by royarzun** [comment]
Is this not going to be merged?

**Comment by islam-kamel** [comment]
maybe have this package archived

**Comment by brandondunc94** [comment]
Let's get this merged please!

**Comment by islam-kamel** [comment]
https://github.com/islam-kamel/django-rest-framework-social-oauth2

**Pull request merged**
